#!/usr/bin/env bash

if
  [[ -s "/Users/owner/.rvm/gems/ruby-2.0.0-p353@global/environment" ]]
then
  source "/Users/owner/.rvm/gems/ruby-2.0.0-p353@global/environment"
  exec bundle "$@"
else
  echo "ERROR: Missing RVM environment file: '/Users/owner/.rvm/gems/ruby-2.0.0-p353@global/environment'" >&2
  exit 1
fi
