#!/usr/bin/env bash

if
  [[ -s "/Users/owner/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/gems/2.0.0/environment" ]]
then
  source "/Users/owner/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/gems/2.0.0/environment"
  exec rails "$@"
else
  echo "ERROR: Missing RVM environment file: '/Users/owner/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/gems/2.0.0/environment'" >&2
  exit 1
fi
